# Generated by Django 4.2.7 on 2023-11-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermeros', '0004_enfermero_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
